name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: gcc teste_calculadora.c -o teste_calculadora
    - name: execute
      run: ./teste_calculadora
